services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/mosquitto/config

  mqtt-subscriber:
    build: ./mqtt-subscriber
    depends_on:
      - mqtt
    volumes:
      - ./mqtt-subscriber:/app