import type { Metadata } from "next";
import "./globals.css";
import { geistSans } from "@/lib/font";

export const metadata: Metadata = {
  title: "13521132 - Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} min-h-screen min-w-[353px] antialiased`}>{children}</body>
    </html>
  );
}
